### ISSUE TITLE
"npm run dev" fails on Windows

### ISSUE THREAD

**Issue by servusdei** [D-Mobilelab/game-sdk#15] opened 2017-03-31 16:15 UTC
"npm run dev" on windows fails untill I changed "NODE_ENV by "SET NODE_ENV" in package.json.

**Comment by eatsjobs** [comment] 2017-04-03 09:24
Hi thanks for reporting. we're on it.

**Comment by eatsjobs** [comment] 2017-04-03 12:54
@servusdei The problem is now fixed with the version 2.3.1. You can git pull the master branch and run "npm run dev". Be sure to have your NODE_PATH environment variable set to "%USERPROFILE%\AppData\Roaming\npm" or where node is installed on your system.

**Closed by eatsjobs** 2017-04-03 12:54 UTC
